[package]
name = "cec-example-cli"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"

[dependencies]
cec-rs = { path = "../.." }
env_logger = "0.10.0"
log = "0.4.8"

[[bin]]
name = "cec-example-cli"
path = "bin.rs"
